### ISSUE TITLE
Error when using models based on complex SQL views

### ISSUE THREAD

**Issue by jmeinken** [chop-dbhi/serrano#271]
I'm building Harvest over an existing MySQL database.  Rather than change the database structure, I've been using views to reorganize the data the way I want to use it in the Harvest application.  I then build my Django models using the views.

I've noticed that view fields built from conditional SQL expressions (IF and CASE WHEN) don't work.  For example using following view in Harvest, view_field1 will work fine, but view_field2 will throw an error when it is accessed from the website in query view.

    CREATE VIEW my_view AS
    SELECT id,
    view_field1,
    (CASE
        WHEN age <= 12
            THEN 'child'
        WHEN age <= 19
            THEN 'teen'
        ELSE 'adult'
    END) AS view_field2,
    FROM my_table;

The error is thrown from Serrano in resources/fields/dist.py on line 99:

    length = len(stats)

It works fine if the below block of code is commented out, but of course that creates errors for other types of fields:

    if not params['nulls']:
        q = Q()
        for field in groupby:
            q = q | Q(**{field: None})
        stats = stats.exclude(q)

**Comment by bruth** [comment]
@jmeinken Can you call the `DataField.dist()` method for that `CASE...WHEN` field to see if it throws an error? Also can you post the traceback for either (or both) exceptions? Thanks.

**Comment by jmeinken** [comment]
Yes, `DataField.dist()` also throws the same error.

I do have my system working, but it's not really an elegant solution.  Basically I only apply modifications to `stats` if it's not going to generate an error.

    if not params['nulls']:
        q = Q()
        for field in groupby:
            q = q | Q(**{field: None})
        stats_temp = stats.exclude(q)

    try:
        length_test = len(stats_temp)
        stats = stats_temp
    except Exception as e:
        print "Handled exception related to using SQL view instead of SQL table: ", e

    ...

Here are the stack traces for the error generated from the website and the error generated from DataField.dist() in command line.  These are both on a SQL view field that uses a `CASE WHEN` expression:


Internal Server Error: /api/fields/17/dist/
Traceback (most recent call last):
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/restlib2/resources.py", line 281, in __call__
    return self.dispatch(request, *args, **kwargs)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/restlib2/resources.py", line 292, in dispatch
    response = method_handler(request, *args, **kwargs)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/serrano/resources/field/dist.py", line 99, in get
    length = len(stats)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/avocado/stats/agg.py", line 64, in __len__
    return len(self._construct())
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 106, in __len__
    self._result_cache = list(self.iterator())
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1018, in iterator
    for row in self.query.get_compiler(self.db).results_iter():
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Truncated incorrect INTEGER value: 'N/A'

    >>> from avocado.models import DataField
    >>> fields = DataField.objects.all()
    >>> fields[266].dist()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/avocado/core/cache/model.py", line 130, in inner
    return cache_proxy.get_or_set(self, args=args, kwargs=kwargs)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/avocado/core/cache/proxy.py", line 45, in get_or_set
    data = self.func(instance, *args, **kwargs)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/avocado/models.py", line 660, in dist
    return tuple(queryset)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 108, in __len__
    self._result_cache.extend(self._iter)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1162, in iterator
    for row in self.query.get_compiler(self.db).results_iter():
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/home/john/harvest/control2-env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Truncated incorrect INTEGER value: 'N/A'

**Comment by bruth** [comment]
Hmm. Are you using the correct model field type for those `CASE WHEN` expressions? I have very limited knowledge about MySQL, but I came across this StackOverflow [answer](http://stackoverflow.com/a/12741223/407954) about this warning and an explicit `CAST` seems to be necessary so values can be compared correctly. Mind updating your views to explicit cast to a varchar?

**Comment by jmeinken** [comment]
That was it.  I tested it today with an explicit `CAST` and it worked fine.  Given that the field data type is already defined in the Django model, it might be nice if explicit casting in the database wasn't required.  But it's not really a bug, and I'll leave it up to you if you want to close this issue.  Thanks

**Comment by bruth** [comment]
Glad it works. The issue here was that the view column was not explicitly casted to the correct type. This isn't something that Django (or Harvest) could do since it's in the view definition and applying casts on every query would be verbose and possibly wasteful. That being said I am not sure if this is just a MySQL nuance. I've used `CASE WHEN` in Postgres without needing to do explicit casts.
